
version: '3.8'
services:

  nestjs-starter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    depends_on:
      - postgres 


  postgres:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: